server:
  port: 9001
spring:
  datasource:
    url: jdbc:mysql://112.124.39.72:3306/distributed_system_lab?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT
    username: root
    password: Xcm1115Ljy0625
  jpa:
    show-sql: true



mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml

saServer:
  id: 1
  name: 华东服务器
  api: /park
  maxsize: 100

websocket:
  maxTimeout: 120000

register:
  onlineapi: ws://127.0.0.1:9000/server/online/